import { searchTimeline } from '../aegis-synthetic-coach/coach-engine.mjs';
import { SYNTHETIC_DATASET } from '../aegis-synthetic-coach/fixtures.mjs';
import { $, escapeHtml, icon, renderStatusGrid, runtimeState } from './ui-utils.mjs';

export function renderTimeline(state, query = '') {
  const rows = searchTimeline(SYNTHETIC_DATASET, query, state.permissions);
  const items = rows.map((row) => `<article class="timeline-row"><span class="timeline-icon">${icon(row.domain)}</span><div><p class="eyebrow">${escapeHtml(row.domain)}</p><h3>${escapeHtml(row.title)}</h3><p>${escapeHtml(row.detail)}</p></div><time>${escapeHtml(row.at)}</time></article>`).join('') || '<p class="empty-state">No synthetic timeline entries match this search.</p>';
  $('#timeline-view').innerHTML = `<section class="view-heading"><p class="eyebrow">My day</p><h1>Everything in one visible flow.</h1><p>Searches only the in-memory synthetic fixture. Nothing is uploaded, connected, or silently saved.</p></section><div class="search-shell"><input id="timeline-search" type="search" placeholder="Search synthetic tasks, calendar, balance, or recovery" value="${escapeHtml(query)}"><span>${rows.length} result${rows.length === 1 ? '' : 's'}</span></div><section class="timeline-list">${items}</section>`;
  $('#timeline-search')?.addEventListener('input', (event) => renderTimeline(state, event.target.value));
}

export function renderPermissions(state) {
  const labels = { calendar:['Synthetic Calendar','Demo event titles and times'], tasks:['Synthetic Tasks','Demo task titles, priorities, and due times'], finance:['Synthetic Financial Snapshot','Demo balances and seven-day projection'], wellness:['Synthetic Wellness','Demo sleep, hydration, and movement'] };
  const cards = Object.entries(labels).map(([domain,[title,detail]]) => `<article class="permission-card"><div class="permission-icon">${icon(domain)}</div><div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(detail)}</p><small>In-memory only · advisory access</small></div><label class="switch"><input type="checkbox" data-domain="${domain}" ${state.permissions[domain] ? 'checked' : ''}><span></span></label></article>`).join('');
  $('#permissions-view').innerHTML = `<section class="view-heading"><p class="eyebrow">Your boundaries</p><h1>You decide what Champion may understand.</h1><p>These switches affect only the included synthetic fixture and reset when the page reloads.</p></section><section class="permission-grid">${cards}</section><section class="boundary-panel"><h2>Real connections remain locked</h2><p>OAuth, provider tokens, Gmail, real calendars, bank accounts, health records, background synchronization, and autonomous actions are prohibited in this build.</p></section>`;
  document.querySelectorAll('.switch input').forEach((input) => input.addEventListener('change', () => { const domain = input.dataset.domain; state.permissions[domain] = input.checked; state.audit.record(input.checked ? 'Enabled synthetic domain' : 'Disabled synthetic domain', { domain, targetId:domain }); renderPermissions(state); }));
}

export function renderAudit(state) {
  const entries = state.audit.list();
  const rows = entries.map((entry) => `<article class="audit-row"><span>${icon(entry.domain)}</span><div><h3>${escapeHtml(entry.event)}</h3><p>${escapeHtml(entry.domain)} · ${escapeHtml(entry.result)}</p></div><time>${escapeHtml(entry.at)}</time></article>`).join('') || '<p class="empty-state">No synthetic session activity has been recorded yet.</p>';
  $('#audit-view').innerHTML = `<section class="view-heading"><p class="eyebrow">Visible activity</p><h1>Nothing happens in the dark.</h1><p>The session log records minimized event metadata only. It does not store source payloads, recommendation evidence, passphrases, or credentials.</p></section><div class="audit-toolbar"><span>${entries.length} session event${entries.length === 1 ? '' : 's'}</span><button id="clear-audit" class="ghost-button">Clear session activity</button></div><section class="audit-list">${rows}</section>`;
  $('#clear-audit')?.addEventListener('click', () => { state.audit.clear(); renderAudit(state); });
}

export function renderSystem() {
  const runtime = runtimeState();
  const installed = runtime.standalone ? 'Standalone' : 'Browser review';
  const workerReady = runtime.serviceWorker === 'registered' ? 'Registered' : escapeHtml(runtime.serviceWorker);
  $('#system-view').innerHTML = `<section class="view-heading"><p class="eyebrow">Shield Room</p><h1>Your protection, stated plainly.</h1><p>This is where the technical truth lives. No cloud capability is implied, and no safety boundary is hidden behind the BioCore experience.</p></section>${renderStatusGrid()}<section class="system-section"><h2>Runtime readiness</h2><p>These checks describe the current browser session. They do not certify the application for personal data.</p><div class="readiness-grid"><article class="readiness-card"><small>Display mode</small><strong class="safe">${escapeHtml(installed)}</strong></article><article class="readiness-card"><small>Service worker</small><strong class="safe">${workerReady}</strong></article><article class="readiness-card"><small>Worker lifecycle</small><strong class="safe">${escapeHtml(runtime.workerState)}</strong></article><article class="readiness-card"><small>Vault state</small><strong class="locked">${escapeHtml(runtime.vault)}</strong></article></div></section><section class="system-section"><h2>Locked boundaries</h2><div class="system-list"><article><span>✓</span><div><strong>External network disabled</strong><small>Content Security Policy blocks runtime connections.</small></div><span class="system-state">Locked</span></article><article><span>✓</span><div><strong>No AWS runtime</strong><small>No AWS SDK, credential, organization, resource, or deployment path is included.</small></div><span class="system-state">Locked</span></article><article><span>✓</span><div><strong>No real accounts</strong><small>No OAuth, provider token, email, bank, calendar, health, wearable, or messaging connection.</small></div><span class="system-state">Locked</span></article><article><span>✓</span><div><strong>No consequential actions</strong><small>No purchases, transfers, messages, deletions, or account changes.</small></div><span class="system-state">Locked</span></article></div></section>`;
}
